// src/utils/constants.js

export const ACTIONS = {
  SET_ACTIVE_TASK_TYPE: 'SET_ACTIVE_TASK_TYPE',
  TOGGLE_CONDITION: 'TOGGLE_CONDITION',
  SET_NUMERIC_CONDITION: 'SET_NUMERIC_CONDITION',
  INCREMENT_DURATION: 'INCREMENT_DURATION',
  DECREMENT_DURATION: 'DECREMENT_DURATION',
  SET_START_DATE: 'SET_START_DATE',
  SET_COMPLETION_DATE: 'SET_COMPLETION_DATE',
  SET_PRIMARY_DATE: 'SET_PRIMARY_DATE',
  SET_CONDITIONS: 'SET_CONDITIONS',
};
